server:
  port: 8086

spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:mysql://localhost:3306/analytics_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: hari@2509
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  secret: 9a4f2c8d3b7a1e5f8c6b4d2e9f0a1b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
