from services.eta_service import ETAService
from services.route_service import RouteOptimizationService
from services.maintenance_service import MaintenancePredictionService
from services.fuel_service import FuelPredictionService
from services.driver_service import DriverAnalysisService
from services.delay_service import DelayPredictionService
from services.vehicle_health_service import VehicleHealthService
